### ISSUE TITLE
Question concerning Packaging Windows Captive Runtime

### ISSUE THREAD

**Issue by yozef** [joshtynjala/setup-adobe-air-action#3]
I'm curious is this Github Action would allow me to Package Windows Captive Runtime AIR Desktop Apps?

I have been trying to avoid packaging once for Mac and again for Windows from the same source code. Could this be a path to investigate further into with this repo?

**Comment by ULSashido** [comment]
I tried: https://github.com/ULSashido/DemoAppGitHubActions

I created a custom Workflow, pasted a very similar yml file to whats included in this projects' yml file. I expected it to do something after a commit. I updated some info to reflect my source code, example `air-version: "30.0"`

Then, I added all the `node_modules`, still got nothing after pushing some code into the project.
I think I'm missing something?

**Comment by ULSashido** [comment]
**Update 1:** I think I got the Windows & Mac working (at least showing a check mark, and logs seem to complete the job): https://github.com/ULSashido/DemoAppGitHubActions/actions/runs/1177838520

However, I don't know **where is the generated package**?

Even though no error was thrown when using AIR 30.0, I noticed in the node file it tries to construct a URL for 30.0 that is not available on Adobe for AIR 30.0, only `air-version: "32.0"` is available from there, so I changed the Project to use 32.0, and updated YML file to use 32.0 - still .exe nor .dmg file for the AIR app can be found (I expected it in the Project on Github, maybe in `/bin/...`) ?

**Update 2:** Seems one extra step is required, which is to upload the packaged App back into repo with such an action: https://github.com/marketplace/actions/upload-asset-to-release

However the question would remain, **where would that executable reside on VM after packaging?**

**Comment by joshtynjala** [comment]
I know that these questions are old, but just for completeness, I thought I'd answer before closing.

> I'm curious is this Github Action would allow me to Package Windows Captive Runtime AIR Desktop Apps?

This Github Action installs the Adobe AIR SDK, which includes the **adt** executable. This executable allows you to package an AIR app. It's the same one you'd use on your local computer in a terminal, and it is used by IDEs like Flash Builder, IntelliJ IDEA, vscode-as3mxml, etc.

> where would that executable reside on VM after packaging?

When you run the **adt -package** command, you are required to include an output path where the executable should be created. That's the path you are looking for. It's the same as if you were running **adt** on your local computer.
